# Shell variables
# Generated by 'wal'
wallpaper='/home/misko/Images/Wallpapers/Wallpaper8.jpg'

# Special
background='#201213'
foreground='#d0dbe0'
cursor='#d0dbe0'

# Colors
color0='#201213'
color1='#4B6C93'
color2='#917C97'
color3='#6A8FAA'
color4='#7CB1C4'
color5='#A9B0B1'
color6='#F4D4A4'
color7='#d0dbe0'
color8='#91999c'
color9='#4B6C93'
color10='#917C97'
color11='#6A8FAA'
color12='#7CB1C4'
color13='#A9B0B1'
color14='#F4D4A4'
color15='#d0dbe0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
