# Shell variables
# Generated by 'wal'
wallpaper='/home/misko/Images/Wallpaper5.jpg'

# Special
background='#010100'
foreground='#ecd8a6'
cursor='#ecd8a6'

# Colors
color0='#010100'
color1='#887239'
color2='#94803F'
color3='#A08743'
color4='#AE9248'
color5='#D2AE56'
color6='#E4BC5D'
color7='#ecd8a6'
color8='#a59774'
color9='#887239'
color10='#94803F'
color11='#A08743'
color12='#AE9248'
color13='#D2AE56'
color14='#E4BC5D'
color15='#ecd8a6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
