#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import socket
import struct
import sys
import traceback


RUN_PATH = u'/home/misko/Documents/Apps/idea-IU-211.7142.45/bin/idea.sh'

def process_args(argv):
     args = []
 
     skip_next = False
     for i, arg in enumerate(argv[1:]):
         if skip_next:
             args.append(arg)
             skip_next = False
         else:
             path = arg
             if ':' in arg:
                 file_path, line_number = arg.rsplit(':', 1)
                 if line_number.isdigit():
                     args.append('-l')
                     args.append(line_number)
                     path = file_path
             args.append(os.path.abspath(path))
 
     return args

ide_args = process_args(sys.argv)
bin_file = os.path.split(RUN_PATH)[1]
os.execv(RUN_PATH, [bin_file] + ide_args)

